#!/bin/sh

VERSION=2.0.rc2

if test -f version
then
	PEDIS_VERSION=$(cat version | awk -F'-' '{print $1}')
	PEDIS_RELEASE=$(cat version | awk -F'-' '{print $2}')
else
	DATE=$(date +%Y%m%d)
	GIT_COMMIT=$(git log --pretty=format:'%h' -n 1)
	PEDIS_VERSION=$VERSION
	# For custom package builds, replace "0" with "counter.your_name",
	# where counter starts at 1 and increments for successive versions.
	# This ensures that the package manager will select your custom
	# package over the standard release.
	PEDIS_BUILD=0
	PEDIS_RELEASE=$PEDIS_BUILD.$DATE.$GIT_COMMIT
fi

echo "$PEDIS_VERSION-$PEDIS_RELEASE"
mkdir -p build
echo "$PEDIS_VERSION" > build/PEDIS-VERSION-FILE
echo "$PEDIS_RELEASE" > build/PEDIS-RELEASE-FILE
